---
# tasks file for tshark-listener
- name: install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
  - tshark
  - tmux
  # https://packetlife.net/blog/2010/mar/19/sniffing-wireshark-non-root-user/
- name: create group tshark for dumpcap access
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ zed_worker_group }}"
    - tshark
- name: add user to tshark group
  ansible.builtin.user:
    name: "{{ tshark_user_name }}"
    group: "{{ zed_worker_group }}"
    groups: "{{ zed_worker_group }}, tshark"
    shell: /bin/bash
    state: present
- name: set group for dumpcap
  ansible.builtin.file:
    path: /usr/bin/dumpcap
    mode: '0750'
    group: tshark
- name: set capabilities of dumpcap
  ansible.builtin.command:
    cmd: setcap cap_net_raw,cap_net_admin=eip /usr/bin/dumpcap
# Unable to get this to work.
# - name: set capabilities of dumpcap
#   capabilities:
#     path: /usr/bin/dumpcap
#     capability: "{{ item }}"
#     state: present
#   with_items:
#   - cap_net_raw+eip
#   - cap_net_admin+eip
- name: Create work directory for tshark buffer files.
  ansible.builtin.file:
    path: "{{ tshark_buffer_dir }}"
    owner: "{{ tshark_user_name }}"
    group: "{{ zed_worker_group }}"
    mode: '0770'
    state: directory
- name: install rc.local template to start capture on reboot
  ansible.builtin.template:
    src: ./templates/rc.local.j2
    dest: /etc/rc.local
    mode: '0755'
    owner: root 
    group: root
  notify: run rc.local
- name: set bash shell for cron
  ansible.builtin.cron:
    name: SHELL
    user: "{{ tshark_user_name }}"
    env: yes
    job: /bin/bash
# - name: launch tmux session ~ tmux attach-session
#   ansible.builtin.cron:
#     name: launch tmux session for user
#     user: "{{ tshark_user_name }}"
#     special_time: reboot
#     job: tmux new-session -d -s tshark && tmux set-option -t tshark remain-on-exit on && tmux new-window -d -n 'tsharkCapture' -t tshark:1 'tshark {{ tshark_options }}'

- name: install tshark_watchdog.sh
  ansible.builtin.template:
    src: tshark_watchdog.sh.j2
    dest: "{{tshark_watchdog_script}}"
    mode: '0770'
    owner: "{{ tshark_user_name }}" 
    group: tshark
- name: crontab run tshark_watchdog.sh every minute
  ansible.builtin.cron:
    name: tshark_watchdog.sh
    user: "{{ tshark_user_name }}"
    minute: '*'
    job: "{{ tshark_watchdog_script }}"
