---
# tasks file for zed
- name: add groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items: 
    - "{{ zed_lake_group }}"
    - "{{ zed_users_group }}"
    - "{{ pcap_access_group }}"
- name: add user to groups
  ansible.builtin.user:
    name: "{{ zed_worker_user }}"
    groups: "{{ pcap_access_group }}, {{ zed_users_group }}"
    shell: /bin/bash
    state: present

- name: create /zed directory
  ansible.builtin.file:
    path: /zed
    state: directory
    owner: root
    group: "{{ zed_users_group }}"
    mode: '0750'

- name: install unzip package
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
  - unzip

- name: Extract zed and zq to /usr/local/bin
  ansible.builtin.unarchive:
    src: "{{ zed_release }}"
    dest: /usr/local/bin
    remote_src: yes

- name: Set permissions on zq
  ansible.builtin.file:
    path: /usr/local/bin/zq
    owner: root
    group: "{{ pcap_access_group }}"
    mode: '0755'

- name: Set permissions on zed 
  ansible.builtin.file:
    path: /usr/local/bin/zed
    owner: root
    group: "{{ pcap_access_group }}"
    mode: '0755'

## Brimcap

- name: Create the brimcap directory if it does not exist
  ansible.builtin.file:
    path: "{{ brimcap_path }}"
    state: directory
    group: "{{ pcap_access_group }}"
    mode: '0755'
- name: Unarchive the brimcap release
  ansible.builtin.unarchive:
    src: "{{ brimcap_release }}"
    dest: /opt/
    remote_src: yes
- name: Recursively change ownership of /opt/brimcap
  ansible.builtin.file:
    path: "{{ brimcap_path }}"
    state: directory
    recurse: yes
    owner: root
    group: "{{ pcap_access_group }}"
    mode: '0755'

- name: Create a symbolic link for brimcap
  ansible.builtin.file:
    src: "{{ brimcap_path }}/brimcap"
    dest: /usr/local/bin/brimcap
    group: "{{ pcap_access_group }}"
    state: link

- name: Create a directory for runner
  ansible.builtin.file:
    dest: /home/runner/
    state: directory
    owner: root
    group: "{{ pcap_access_group }}"
    mode: '0755'

- name: Create a symbolic link for suricata
  ansible.builtin.file:
    src: "{{ brimcap_path }}/suricata"
    dest: /home/runner/suricata
    group: "{{ pcap_access_group }}"
    state: link

- name: Create a symbolic link for zeek
  ansible.builtin.file:
    src: "{{ brimcap_path }}/zeek"
    dest: /home/runner/zeek
    group: "{{ pcap_access_group }}"
    state: link

# - name: Update /etc/environment for brim directory
#   lineinfile:
#     dest: /etc/environment
#     line: "PATH=\"{{ brimcap_path }}:$PATH\""
#     owner: root
